export {default as MainScreen} from "./MainScreen"
export {default as LoginCliente} from "./Login_Cliente"
export {default as MinhaConta} from "./Minha_Conta"
export {default as MinhaContaDados} from "./Minha_Conta_Dados"
export {default as Estoque} from "./Estoque"
export {default as Cardapio} from "./Cardapio"
export {default as Cardapio_ADM} from "./Cardapio_ADM"
export {default as EditarCarnes} from "./Cardapio_ADM/Editar_Carnes"